description: >
  CTP431 Final Project Music to Text to Music (M2T2M) <br>
  Donghyeon Choi, Seunghyun Cho <br>
  KAIST Graduate School of AI Semiconductor, 
  KAIST School of Electrical Engineering
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

